version: "2"
services:
  
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: trackingDetector
      MINIO_ROOT_PASSWORD: Strong#Pass#2022
    command: server --console-address ":9001" /data
  
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongo_storage:/data/db

  entrypoint:
    build: ./entrypoint
    command: npm start
    ports:
    - "3000:3000"

  training:
    build: ./training
    command: python handler.py
    restart: always


volumes:
  minio_storage: {}
  mongo_storage: {}