version: "2"
services:
  
  nginx:
    build: ./gateway
    ports:
      - "80:80"
    depends_on:
      - db
      - minio
      - server
      - training

  minio:
    image: minio/minio
    container_name: minio
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: trackingDetector
      MINIO_ROOT_PASSWORD: Strong#Pass#2022
    command: server --console-address ":9001" /data
  
  db:
    image: mongo:latest
    container_name: db
    volumes:
      - mongo_storage:/data/db

  server:
    build: ./server
    container_name: server
    depends_on:
      - db
      - minio

  training:
    build: ./training
    container_name: training
    command: python handler.py
    depends_on:
      - db
      - minio
    restart: always


volumes:
  minio_storage: {}
  mongo_storage: {}